version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3100:3100"
    environment:
      - REACT_APP_API_URL=http://192.168.50.29:5000
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:4000"
    environment:
      - DB_HOST=db
      - DB_USER=kbuser
      - DB_PASS=supersecure
      - DB_NAME=stocktracker
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: stocktracker
      POSTGRES_USER: kbuser
      POSTGRES_PASSWORD: supersecure
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
